### ISSUE TITLE
Support 2factor auth in FlowAuth

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#121]
Because FlowAuth is potentially much more publicly deployed than other components, and is the gatekeeper for access to the rest of any given FlowKit deployment, it should of course be as secure as possible.

Supporting 2factor auth would be a clear boost here.

**Comment by greenape** [comment]
Open question: should 2factor be mandatory, or optional?

**Comment by maxalbert** [comment]
I always find it most useful to be as restrictive as possible by default, because then exceptions can be assessed on a case-by-case basis as they arise (if ever).

If instead you make it optional then people will typically choose the easy option. As a result, there is little to no incentive to give feedback; it makes it very difficult to assess the consequences of not using it; it's virtually impossible to enforce it later if you decide that you _should_ have made it mandatory from the start.

So my preference would be to make it mandatory in the first instance, but write the implementation in such a way that making it optional in the future is still easy for us if there should be a need to support this.
