### ISSUE TITLE
Change default API behaviour to return p-codes instead of names

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#126]
At present the data returned when getting anything via FlowClient contains the administrative name, but should instead return the [p-code](https://humanitarian.atlassian.net/wiki/spaces/imtoolbox/pages/222265609/P-codes) as this is more generally useful and doesn't have the same risks around collisions etc.

Right now, the default behaviour internally within FlowMachine is to use the administrative name, so my feeling is the change should happen there, rather than at the API layer.

**Comment by maxalbert** [comment]
Agreed on both counts. We will likely still want a way of returning data by administrative name (either  in addition to or instead of p-code), but internally everything should use unique IDs that have no risk of collision. Likely we probably even want to handle things internally using gid rather than p-code because we have control over it and can ensure it's unique?

**Comment by greenape** [comment]
Yep, that sounds sensible on both counts to me.

What I'm thinking is we change the behaviour now, and then roll the use of gids internally and getting other data about the place into a broader effort to clean up the way we handle aggregation units in FlowMachine. (I'm open to being argued around on that though.)
