### ISSUE TITLE
Column types

### ISSUE THREAD

**Issue by josh-gree** [Flowminder/FlowKit#181]
We should have a think about the best types for the columns in the events schemas. Some initial thoughts!

- id columns - these make use of the md5 function which always returns a string of length 32. We should therefore use a `char(32)` type.
- duration columns - are these ever floats? If not we should use one of the integer types. Even if they are floats who cares about fractions of a second on a call we should just truncate to an int? 
- network columns - generally one of three possibilities - should we use a PG enum here?
- location_id - These should conform to the CGI code spec - this has a max length of 16 I think so this could be `varchar(16)` 
- operator, network and tac columns - we will never do any arithmetic on these so should they be numeric? Perhaps numeric is better than text in terms of space but we should have some fixed length?

**Comment by greenape** [comment]
- ID columns: while we do often generate these, they are sometimes operator supplied, so not necessarily char(32). Could of course md5 them to enforce that I suppose.
- Duration usually comes in fractional minutes as far as I recall, what's the argument for tossing info here?
- location_id - can you drop a link to the CGI spec? I'm not uber-convinced that the idents one might expect to actually _get_ from an operator will always conform to this.
- operator, network, tac - these shouldn't be numeric, you're right. They're not _numbers_ they're numeric strings

**Comment by josh-gree** [comment]
ID columns: For consistency - we should always generate and should be md5 of same columns regardless of operator. 
duration: Thought it was seconds - in which seconds who cares if a call lasted 123 seconds or 123.2 seconds!? If minutes then yeah wouldn't throw away. 
location_id: Yeah I'm not either but @chrisjbrooks seems to think so.

**Comment by maxalbert** [comment]
Re ID columns, location IDs and similar identifiers: how about we move this information out into separate dimension tables and use numeric IDs for the `subscriber_id` and `location_id` columns in the events table instead?

We're kinda doing this already for `location_ids` with the infrastructure tables, except that we're still using the full string of the location ID as the identifier in `events.calls`.

Advantages: 
- Reduced disk storage (a bigint takes much less space than a 32-character string).
- Likely improved performance (should be faster to iterate over a column with integers as opposed to long strings, although we'd have to profile it to know how much of a difference it makes).
- Allows to have consistent data types in the `events.calls` table independent of the operator; any such differences can be dealt with in the dimension tables.
- Much easier to get a better overview of the full subscriber base because it's readily available in the separate table (and we can potentially associated additional info/metrics with it).
- Might make dealing with versioned information (e.g. versioned cells) easier in the future.

**Comment by josh-gree** [comment]
I think for both `subscriber_id` and `location_id` such tables would be a great idea. As you say we already basically do this for `location_id` - doing it for `subscriber_id` I think would have lots of added benefits.

- When and where was a subscriber last seen?
- When and where were they first seen?
- What do we believe is their current "HomeLocation"?
- ...

**Comment by greenape** [comment]
I think this is satisfied as of closing #640
