### ISSUE TITLE
The admin section of the docs is missing

### ISSUE THREAD

**Issue by geekysquirrel** [Flowminder/FlowKit#3152]
**Describe the bug**
https://flowkit.xyz/install/administrator returns a 404.

**Version**
c4dc74f2e99224ae9a98f303a61a29b73f075cb4

**To Reproduce**
Visit https://flowkit.xyz/install/administrator

**Expected behavior**

**Screenshots**
![Screenshot 2020-10-19 at 11 17 19](https://user-images.githubusercontent.com/15160279/96433755-2e881380-11fd-11eb-860a-3a51deaffb07.png)

**Comment by jc-harrison** [comment]
Oops! The correct URL is https://flowkit.xyz/administrator. Looks like there's a broken relative link somewhere.

**Comment by geekysquirrel** [comment]
That would be in the "installation requirements" section of https://flowkit.xyz/install/

**Comment by geekysquirrel** [comment]
Looking at the code it should work, as the links are relative from the install.md to the admin/developer sections. However, the deployed docs seem to have an extra directory "install" in between, which breaks the links. Not sure where this should be changed.

**Comment by jc-harrison** [comment]
I think the issue here is that when Mkdocs builds the docs, it will convert '{source}/install.md' to '{root}/install/index.html', so then a relative link from install.md to 'administrator' will end up pointing to '{root}/install/administrator/', and the required relative link here should actually be '../administrator'.

When linking from one source file to another source file, Mkdocs is smart enough to change the link in the output file appropriately. The problem here is that the link just points to a directory ('administrator'), rather than an actual source file ('administrator/index.md'), so Mkdocs leaves it unchanged when building the docs. So changin the link from 'administrator' to 'administrator/index.md' in install.md should fix this.
