### ISSUE TITLE
Rebuild & deploy docs on every merge to master?

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#395]
Currently the docs only get re-deployed when a tagged version is pushed. This makes it a little confusing when trying to find information that has already been merged to the docs in current master but isn't present in the deployed docs yet. There is probably a good reason for the current behaviour, but I feel it would be more useful to have the docs re-deployed on every merge to master, too. Or would this extend the build time by too much?

**Comment by jch1g10** [comment]
The deployed docs should correspond to the FlowKit version we are encouraging people to use, which is currently the latest master commit, so from that perspective it would make sense to deploy the docs on every merge to master. On the other hand, deploying the docs only when a tag is pushed means that the deployed docs will correspond to the latest release, and we can always manually deploy the docs if there's a significant change. I'm sure there are other factors that I haven't considered.

I wouldn't imagine it would significantly extend the build time, since the docs are already built as part of the CI build, just not deployed.

**Comment by maxalbert** [comment]
Yes, you are right that it is best to have the deployed docs correspond to the latest release (rather than master) - even if the two are almost identical in our case, at least for the time being.

I guess the "correct" solution in the medium term is to provide different versions of the docs (at the very least "stable" and "dev", but ideally archived versions for every release too), similar to how pandas, numpy, etc. do it.

I'll close this issue and we can open a separate one for versioned docs.
