### ISSUE TITLE
Explore feasibility of trimming docker images where possible

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#397]
Some of the docker images are fairly large (e.g. flowmachine is > 1.5 GB). This is typically because they are based on standard images (e.g. `python:3.7`) which in turn may contain a full Debian/Ubuntu distribution, sometimes with additional developer packages included. It would be good to explore which of our images can be based on smaller docker images (such as alpine-based ones). In some cases (e.g. flowbd) this is not easily possible, but for flowmachine and probably others it may be.

**Comment by greenape** [comment]
For ref - the original reason to use the Debian based Postgres for FlowDB was because of the need to compile some extensions and added bits. That's less relevant now, but the Debian image remains necessary because arbitrary users can't be used with the alpine base image.

Should definitely be doable to slim the others, starting with switching them to alpine.

**Comment by maxalbert** [comment]
Yes agreed, it makes sense to keep FlowDB on the Debian. Re slimming the others, will be good to weigh off the trade-offs to see if it's worth the effort. Switching to Alpine will likely have the advantage of much smaller size but may considerably increase the build time because some Python packages need to be compiled from source if there is no wheel available for Alpine (and _may_ also require more maintenance than the Debian/Ubuntu-based ones for the same reason). Certainly useful to investigate the option, though.

**Comment by maxalbert** [comment]
Actually, `passenger-docker` (or possibly `baseimage-docker`) look like an interesting alternative to alpine.

- https://github.com/phusion/passenger-docker
- http://phusion.github.io/passenger-docker/


- https://github.com/phusion/baseimage-docker
- http://phusion.github.io/baseimage-docker/

**Comment by greenape** [comment]
This (alpine, anyway) is very doable for FlowAPI, but not for FlowAuth right now (https://github.com/tiangolo/uwsgi-nginx-flask-docker#temporarily-not-supported). FlowMachine has a dependency on pandas (although I think, not a required one for the docker container), which obviously makes alpine untenable because of the need to build pandas.
