### ISSUE TITLE
Pin pglast version in setup.py

### ISSUE THREAD

**Issue by greenape** [Flowminder/FlowKit#5704]
I think we should really pin the pglast version, because it is used for query id generation in some cases, and means that an upgrade to pglast could change cache ids unexpectedly.

**Comment by jc-harrison** [comment]
In cases where we're using the prettified SQL for query ID generation, we'd perhaps be better off using [pglast.parser.fingerprint](https://pglast.readthedocs.io/en/v4/parser.html#pglast.parser.fingerprint) so we're not sensitive to changes in formatting style. Although that in itself wouldn't fully resolve this issue, because an upgrade to `libpg_query` may change the [fingerprinting rules](https://github.com/pganalyze/libpg_query/wiki/Fingerprinting).
