### ISSUE TITLE
Worked examples should generate tokens directly in notebook

### ISSUE THREAD

**Issue by maxalbert** [Flowminder/FlowKit#712]
Currently the user must generate a token in flowauth and paste it into the notebook before being able to execute the worked examples. Esp. with the dockerised worked examples being available it would be useful if they used the new `flowkit_jwt_generator` module (once #689 is merged) to generate tokens in the notebooks directly.

**Comment by greenape** [comment]
Yeah, I was debating that with myself - I'm not sure there isn't some merit in _making_ people go through the FlowAuth interface though, because that's what reality will be like. Much more seamless to not do that though :P

**Comment by maxalbert** [comment]
Yeah, that's a good point. If you like we could have one worked example which makes the user go through the full FlowAuth process, but for the other ones it would be good to have it as seamless as possible.

**Comment by jch1g10** [comment]
I agree that it would be good to have a worked example which makes the user go through the full FlowAuth process (perhaps do this in the FlowClient example usage notebook, and use `flowkit_jwt_generator` in all the worked examples).

I also think it would be important to make it clear that using the `flowkit_jwt_generator` module will only work for the demo setup, in case users want to run the worked examples against an actual deployed FlowKit (and similarly, we may want to hide the cells which use `flowkit_jwt_generator` in the docs output).

**Comment by jch1g10** [comment]
I'm still unsure about this. I'm concerned that it may be more confusing, since users will likely use the worked examples as a reference when working with a production FlowKit, and may (unsuccessfully) attempt to use the `flowkit_jwt_generator` module as a result.

Another use-case for the worked examples would be to demonstrate that a production setup has been successfully deployed, and in this situation it's useful to also establish that FlowAuth is working correctly.

Using the `flowkit_jwt_generator` in the dockerised quick-start setup would still make things a little more seamless, but I'm not sure that this outweighs the potential for it to be misleading in other situations (particularly since we also spin up a pre-populated FlowAuth instance in the quick-start setup, to make the token generation process as painless as possible).

@maxalbert I'm adding some more explicit FlowAuth token generation instructions to the worked examples, specifically for the quick-start setup (see PR to appear soon). Is this a sufficient compromise, or would you still prefer that we use the `flowkit_jwt_generator` module?
