### ISSUE TITLE
FLOWDB_HOST not what I expected

### ISSUE THREAD

**Issue by josh-gree** [Flowminder/FlowKit#827]
**Describe the bug**

If I run the following command to spin up flowdb with other containers;

```
 DOCKER_SERVICES="flowdb flowetl flowetl_db" make up-no_build
```

Then the `DOCKER_FLOWDB_HOST` is not set to `flowdb` as I would expect but to `flowdb_testdata` as this is the default in the `Makefile`. In order to specify starting a subset of services with the correct `DOCKER_FLOWDB_HOST` I have to run;

```
FLOWDB_SERVICES=flowdb DOCKER_SERVICES="flowdb flowetl flowetl_db" make up-no_build
```

Specifying `flowdb` twice...And possibly allowing for somebody to do something like;

```
FLOWDB_SERVICES=flowdb DOCKER_SERVICES="flowdb_synthetic_data flowetl flowetl_db" make up-no_build
```

Which would again lead `DOCKER_FLOWDB_HOST` being incorrect. 

Is there not a way of removing the `FLOWDB_SERVICES` env var completely and just finding the name of the `flowdb` service from `DOCKER_SERVICES` if it exists? Also not completely clear why you ever want to have multiple versions of `flowdb` at the same time!?

**Comment by greenape** [comment]
You _should_ just be able to omit flowed from `DOCKER_SERVICES`, so:

`FLOWDB_SERVICES=flowdb DOCKER_SERVICES="flowetl flowetl_db" make up-no_build`

**Comment by josh-gree** [comment]
Am I missing something! You can't though right? Cos `FLOWDB_SERVICES` only gets prefixed to the default `DOCKER_SERVICES` not any `DOCKER_SERVICES`?

**Comment by greenape** [comment]
Shoot, no, you're right.

**Comment by maxalbert** [comment]
Agreed @josh-gree, this is an annoying usability issue. I think the existence of `FLOWDB_SERVICES` was meant to provide an easy way of just switching out the kind of flowdb you want to use (because all the other services _used_ to be fixed and you didn't need to specify them all the time. But now that we have more of them in `DOCKER_SERVICES` that you potentially want to omit (like the worked examples or others, as in you example above) it seems better to just do away with `FLOWDB_SERVICES` and require the user to explicitly set `DOCKER_SERVICES` to the list of services they want to use. I'll change it in the Makefile.

**Comment by greenape** [comment]
```
DOCKER_SERVICES ?= $(FLOWDB_SERVICES) flowapi flowmachine flowauth flowmachine_query_locker flowetl flowetl_db worked_examples
```

to

```
DOCKER_SERVICES ?= flowapi flowmachine flowauth flowmachine_query_locker flowetl flowetl_db worked_examples
DOCKER_SERVICES = $(FLOWDB_SERVICES) $(DOCKER_SERVICES)
```

Or something like that?

**Comment by maxalbert** [comment]
I think given the typical use cases that arise in practie (which weren't quite clear when I wrote that Makefile) it's actually easier and cleaner to completely get rid of `FLOWDB_SERVICES` and only use `DOCKER_SERVICES`. I'll put a PR up and we can discuss there.
